### ISSUE TITLE
BiomesOPlenty Could not read image

### ISSUE THREAD

**Issue by superzanti** [superzanti/TheVerse#2]
Error in line 4288 of the fml-client-latest.log logfile.

```
[15:33:17] [Client thread/ERROR] [BiomesOPlenty/BiomesOPlenty]: Could not read existing image from: C:\Users\sethm\Documents\TheVerse\data\.minecraft\assets\bopexternal\trails\dev_trail. Attempting redownload.

javax.imageio.IIOException: Can't read input file!
	at javax.imageio.ImageIO.read(Unknown Source) ~[?:1.8.0_73]
	at biomesoplenty.client.utils.ExternalTexture.<init>(ExternalTexture.java:51) [ExternalTexture.class:?]
	at biomesoplenty.client.utils.ExternalTextureManager.retrieveExternalTexture(ExternalTextureManager.java:36) [ExternalTextureManager.class:?]
	at biomesoplenty.client.utils.ParticleRegistry.<init>(ParticleRegistry.java:24) [ParticleRegistry.class:?]
	at biomesoplenty.common.eventhandler.BOPEventHandlers.registerClientEventHandlers(BOPEventHandlers.java:79) [BOPEventHandlers.class:?]
	at biomesoplenty.common.eventhandler.BOPEventHandlers.init(BOPEventHandlers.java:37) [BOPEventHandlers.class:?]
	at biomesoplenty.BiomesOPlenty.preInit(BiomesOPlenty.java:68) [BiomesOPlenty.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[15:33:17] [Texture Downloader #1/DEBUG] [BiomesOPlenty/BiomesOPlenty]: Downloading http texture from https://raw.githubusercontent.com/Glitchfiend/BiomesOPlenty/master/trails/dev_trail.png to C:\Users\sethm\Documents\TheVerse\data\.minecraft\assets\bopexternal\trails\dev_trail

[15:33:17] [Client thread/ERROR] [BiomesOPlenty/BiomesOPlenty]: Could not read existing image from: C:\Users\sethm\Documents\TheVerse\data\.minecraft\assets\bopexternal\trails\donator_trail. Attempting redownload.

javax.imageio.IIOException: Can't read input file!
	at javax.imageio.ImageIO.read(Unknown Source) ~[?:1.8.0_73]
	at biomesoplenty.client.utils.ExternalTexture.<init>(ExternalTexture.java:51) [ExternalTexture.class:?]
	at biomesoplenty.client.utils.ExternalTextureManager.retrieveExternalTexture(ExternalTextureManager.java:36) [ExternalTextureManager.class:?]
	at biomesoplenty.client.utils.ParticleRegistry.<init>(ParticleRegistry.java:25) [ParticleRegistry.class:?]
	at biomesoplenty.common.eventhandler.BOPEventHandlers.registerClientEventHandlers(BOPEventHandlers.java:79) [BOPEventHandlers.class:?]
	at biomesoplenty.common.eventhandler.BOPEventHandlers.init(BOPEventHandlers.java:37) [BOPEventHandlers.class:?]
	at biomesoplenty.BiomesOPlenty.preInit(BiomesOPlenty.java:68) [BiomesOPlenty.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_73]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_73]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

```

**Comment by Weikardzaena** [comment]
I'll take a look at this

**Comment by Weikardzaena** [comment]
It looks like the mod recreates these files on launch, and apparently they're actually incorrectly-named .png files.  Renaming them allows them to be opened in an image previewer, but it doesn't fix the problem as they are recreated each time.  Not sure what we can do to fix this other than getting at the source for Biomes O Plenty.

**Comment by Weikardzaena** [comment]
Alright, I got rid of the error, but it needs a script to be run *after* the user clicks the "play" button.  Basically, for whatever reason, the three files that produce the error are deleted every time you click "play," and are re-downloaded a few seconds later after the file not found error.  What I did to fix it was to make a copy of the directory containing the files, and right after the client deleted the files I copied that directory back to where it's supposed to be.  Bam!  No Biomes O Plenty error.  So short of editing the Biomes mod itself, we need to get those files back to where they're supposed to be after they're deleted.  Not sure how to do that though.

**Comment by superzanti** [comment]
Without any fix do you think it's a perfectly save to ignore error? Do you think we will notice any texture problems or anything if we don't fix it?

**Comment by Weikardzaena** [comment]
I don't believe so.  I tried to break it by trying to reproduce some crashes some people reported and I couldn't get it to break.  So I think we can ignore this error.

**Comment by superzanti** [comment]
Yeah I was just wondering if some blocks might be invisible or missing textures.

If not I think we're good.

Closing.
